import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-champions',
  templateUrl: './champions.component.html',
  styleUrls: ['./champions.component.css']
})
export class ChampionsComponent implements OnInit {

  champions = [
    {championsId: 'aatrox', rolPrincipal : 'TOP', RP: '975', PI: '6300'},
    {championsId: 'ahri', rolPrincipal : 'MID', RP: '880', PI: '4800'},
    {championsId: 'akali', rolPrincipal: 'MID', RP: '', PI: ''},
    {championsId: 'alistar', rolPrincipal: 'SUPP', RP: '', PI: ''},
    {championsId: 'amumu', rolPrincipal: 'JG', RP: '', PI: ''},
    {championsId: 'anivia', rolPrincipal: 'MID', RP: '', PI: ''},
    {championsId: 'annie', rolPrincipal: 'MID', RP: '', PI: ''},
    {championsId: 'ashe', rolPrincipal: 'ADC', RP: '', PI: ''},
    {championsId: 'aurelionsol', rolPrincipal: 'MID', RP: '', PI: ''},
    {championsId: 'azir', rolPrincipal: 'MID', RP: '', PI: ''},
    {championsId: 'brand', rolPrincipal: 'MID', RP: '', PI: ''},
    {championsId: 'braum', rolPrincipal: 'SUPP', RP: '', PI: ''},
    {championsId: 'caitlyn', rolPrincipal: 'ADC', RP: '', PI: ''},
    {championsId: 'camile', rolPrincipal: 'TOP', RP: '', PI: ''},
    {championsId: 'cassiopeia', rolPrincipal: 'MID', RP: '', PI: ''},
    {championsId: 'chogath', rolPrincipal: 'TOP', RP: '', PI: ''},
    {championsId: 'corki', rolPrincipal: 'ADC', RP: '', PI: ''},
    {championsId: 'darius', rolPrincipal: 'TOP', RP: '', PI: ''},
    {championsId: 'diana', rolPrincipal: '', RP: '', PI: ''},
    {championsId: 'drmundo', rolPrincipal: '', RP: '', PI: ''},
    {championsId: 'draven', rolPrincipal: '', RP: '', PI: ''},
    {championsId: 'ekko', rolPrincipal: '', RP: '', PI: ''},
    {championsId: 'elise', rolPrincipal: '', RP: '', PI: ''},
    {championsId: 'evelynn', rolPrincipal: '', RP: '', PI: ''},
    {championsId: 'ezreal', rolPrincipal: '', RP: '', PI: ''},
    {championsId: 'fiddlesticks', rolPrincipal: '', RP: '', PI: ''},
    {championsId: 'fiora', rolPrincipal: '', RP: '', PI: ''},
    {championsId: 'fizz', rolPrincipal: '', RP: '', PI: ''},
    {championsId: 'galio', rolPrincipal: '', RP: '', PI: ''},
    {championsId: 'gangplank', rolPrincipal: '', RP: '', PI: ''},
    {championsId: 'garen', rolPrincipal: '', RP: '', PI: ''},
    {championsId: 'gnar', rolPrincipal: '', RP: '', PI: ''},
    {championsId: 'gragas', rolPrincipal: '', RP: '', PI: ''},
    {championsId: 'graves', rolPrincipal: '', RP: '', PI: ''},
    {championsId: 'hecarim', rolPrincipal: '', RP: '', PI: ''},
    {championsId: 'heimerdinger', rolPrincipal: '', RP: '', PI: ''},
    {championsId: 'illaoi', rolPrincipal: '', RP: '', PI: ''},
    {championsId: 'irelia', rolPrincipal: '', RP: '', PI: ''},
    {championsId: 'ivern', rolPrincipal: '', RP: '', PI: ''},
    {championsId: 'janna', rolPrincipal: '', RP: '', PI: ''},
    {championsId: 'jarvaniv', rolPrincipal: '', RP: '', PI: ''},
    {championsId: 'jax', rolPrincipal: '', RP: '', PI: ''},
    {championsId: 'jayce', rolPrincipal: '', RP: '', PI: ''},
    {championsId: 'jhin', rolPrincipal: '', RP: '', PI: ''},
    {championsId: 'jinx', rolPrincipal: '', RP: '', PI: ''},
    {championsId: 'kaisa', rolPrincipal: '', RP: '', PI: ''},
    {championsId: 'kalista', rolPrincipal: '', RP: '', PI: ''},
    {championsId: 'karma', rolPrincipal: '', RP: '', PI: ''},
    {championsId: 'karthus', rolPrincipal: '', RP: '', PI: ''},
    {championsId: 'kassadin', rolPrincipal: '', RP: '', PI: ''},
    {championsId: 'katarina', rolPrincipal: '', RP: '', PI: ''},
    {championsId: 'kayle', rolPrincipal: '', RP: '', PI: ''},
    {championsId: 'kayn', rolPrincipal: '', RP: '', PI: ''},
    {championsId: 'kennen', rolPrincipal: '', RP: '', PI: ''},
    {championsId: 'khazix', rolPrincipal: '', RP: '', PI: ''},
    {championsId: 'kindred', rolPrincipal: '', RP: '', PI: ''},
    {championsId: 'kled', rolPrincipal: '', RP: '', PI: ''},
    {championsId: 'kogmaw', rolPrincipal: '', RP: '', PI: ''},
    {championsId: 'leblanc', rolPrincipal: '', RP: '', PI: ''},
    {championsId: 'leesin', rolPrincipal: '', RP: '', PI: ''},
    {championsId: 'leona', rolPrincipal: '', RP: '', PI: ''},
    {championsId: 'lissandra', rolPrincipal: '', RP: '', PI: ''},
    {championsId: 'lucian', rolPrincipal: '', RP: '', PI: ''},
    {championsId: 'lulu', rolPrincipal: '', RP: '', PI: ''},
    {championsId: 'lux', rolPrincipal: '', RP: '', PI: ''},
    {championsId: 'malphite', rolPrincipal: '', RP: '', PI: ''},
    {championsId: 'malzahar', rolPrincipal: '', RP: '', PI: ''},
    {championsId: 'maokai', rolPrincipal: '', RP: '', PI: ''},
    {championsId: 'masteryi', rolPrincipal: '', RP: '', PI: ''},
    {championsId: 'missfortune', rolPrincipal: '', RP: '', PI: ''},
    {championsId: 'mordekaiser', rolPrincipal: '', RP: '', PI: ''},
    {championsId: 'morgana', rolPrincipal: '', RP: '', PI: ''},
    {championsId: 'nami', rolPrincipal: '', RP: '', PI: ''},
    {championsId: 'nasus', rolPrincipal: '', RP: '', PI: ''},
    {championsId: 'nautilus', rolPrincipal: '', RP: '', PI: ''},
    {championsId: 'nidalee', rolPrincipal: '', RP: '', PI: ''},
    {championsId: 'nocturne', rolPrincipal: '', RP: '', PI: ''},
    {championsId: 'nunu', rolPrincipal: '', RP: '', PI: ''},
    {championsId: 'olaf', rolPrincipal: '', RP: '', PI: ''},
    {championsId: 'oriana', rolPrincipal: '', RP: '', PI: ''},
    {championsId: 'ornn', rolPrincipal: '', RP: '', PI: ''},
    {championsId: 'pantheon', rolPrincipal: '', RP: '', PI: ''},
    {championsId: 'poppy', rolPrincipal: '', RP: '', PI: ''},
    {championsId: 'pyke', rolPrincipal: '', RP: '', PI: ''},
    {championsId: 'quinn', rolPrincipal: '', RP: '', PI: ''},
    {championsId: 'rakan', rolPrincipal: '', RP: '', PI: ''},
    {championsId: 'rammus', rolPrincipal: '', RP: '', PI: ''},
    {championsId: 'reksay', rolPrincipal: '', RP: '', PI: ''},
    {championsId: 'renekton', rolPrincipal: '', RP: '', PI: ''},
    {championsId: 'rengar', rolPrincipal: '', RP: '', PI: ''},
    {championsId: 'riven', rolPrincipal: '', RP: '', PI: ''},
    {championsId: 'rumble', rolPrincipal: '', RP: '', PI: ''},
    {championsId: 'ryze', rolPrincipal: '', RP: '', PI: ''},
    {championsId: 'sejuani', rolPrincipal: '', RP: '', PI: ''},
    {championsId: 'shaco', rolPrincipal: '', RP: '', PI: ''},
    {championsId: 'shen', rolPrincipal: '', RP: '', PI: ''},
    {championsId: 'shyvana', rolPrincipal: '', RP: '', PI: ''},
    {championsId: 'singed', rolPrincipal: '', RP: '', PI: ''},
    {championsId: 'sion', rolPrincipal: '', RP: '', PI: ''},
    {championsId: 'sivir', rolPrincipal: '', RP: '', PI: ''},
    {championsId: 'skarner', rolPrincipal: '', RP: '', PI: ''},
    {championsId: 'sona', rolPrincipal: '', RP: '', PI: ''},
    {championsId: 'soraka', rolPrincipal: '', RP: '', PI: ''},
    {championsId: 'swain', rolPrincipal: '', RP: '', PI: ''},
    {championsId: 'syndra', rolPrincipal: '', RP: '', PI: ''},
    {championsId: 'tahmkench', rolPrincipal: '', RP: '', PI: ''},
    {championsId: 'taliyah', rolPrincipal: '', RP: '', PI: ''},
    {championsId: 'talon', rolPrincipal: '', RP: '', PI: ''},
    {championsId: 'taric', rolPrincipal: '', RP: '', PI: ''},
    {championsId: 'teemo', rolPrincipal: '', RP: '', PI: ''},
    {championsId: 'thresh', rolPrincipal: '', RP: '', PI: ''},
    {championsId: 'tristana', rolPrincipal: '', RP: '', PI: ''},
    {championsId: 'trundle', rolPrincipal: '', RP: '', PI: ''},
    {championsId: 'tryndamere', rolPrincipal: '', RP: '', PI: ''},
    {championsId: 'twistedfate', rolPrincipal: '', RP: '', PI: ''},
    {championsId: 'twitch', rolPrincipal: '', RP: '', PI: ''},
    {championsId: 'udyr', rolPrincipal: '', RP: '', PI: ''},
    {championsId: 'urgot', rolPrincipal: '', RP: '', PI: ''},
    {championsId: 'varus', rolPrincipal: '', RP: '', PI: ''},
    {championsId: 'vayne', rolPrincipal: '', RP: '', PI: ''},
    {championsId: 'veigar', rolPrincipal: '', RP: '', PI: ''},
    {championsId: 'velkoz', rolPrincipal: '', RP: '', PI: ''},
    {championsId: 'vi', rolPrincipal: '', RP: '', PI: ''},
    {championsId: 'viktor', rolPrincipal: '', RP: '', PI: ''},
    {championsId: 'vladimir', rolPrincipal: '', RP: '', PI: ''},
    {championsId: 'volibear', rolPrincipal: '', RP: '', PI: ''},
    {championsId: 'warwick', rolPrincipal: '', RP: '', PI: ''},
    {championsId: 'wukong', rolPrincipal: '', RP: '', PI: ''},
    {championsId: 'xayah', rolPrincipal: '', RP: '', PI: ''},
    {championsId: 'xerath', rolPrincipal: '', RP: '', PI: ''},
    {championsId: 'xinzhao', rolPrincipal: '', RP: '', PI: ''},
    {championsId: 'yasuo', rolPrincipal: '', RP: '', PI: ''},
    {championsId: 'yoric', rolPrincipal: '', RP: '', PI: ''},
    {championsId: 'zac', rolPrincipal: '', RP: '', PI: ''},
    {championsId: 'zed', rolPrincipal: '', RP: '', PI: ''},
    {championsId: 'ziggs', rolPrincipal: '', RP: '', PI: ''},
    {championsId: 'zilean', rolPrincipal: '', RP: '', PI: ''},
    {championsId: 'zoe', rolPrincipal: '', RP: '', PI: ''},
    {championsId: 'zyra', rolPrincipal: '', RP: '', PI: ''},
    {championsId: 'Neeko', rolPrincipal: '', RP: '', PI: ''},
  ]

  constructor() { }

  ngOnInit() {
    document.getElementById('championIdRouter');
    console.log('aRouter: ' + document.getElementById('championIdRouter'));
    console.log('aClassRouter: ' + document.getElementsByClassName('championIdRouter'));
  }

}
