import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-history-champs',
  templateUrl: './history-champs.component.html',
  styleUrls: ['./history-champs.component.scss']
})
export class HistoryChampsComponent implements OnInit {

  champions = [
    { championsId: 'aatrox', history: 'prueba' },
    { championsId: 'ahri', history: 'prueba' },
    { championsId: 'akali', history: 'prueba' },
    { championsId: 'alistar', history: 'prueba' },
    { championsId: 'amumu', history: 'prueba' },
    { championsId: 'anivia', history: 'prueba' },
    { championsId: 'annie', history: 'prueba' },
    { championsId: 'ashe', history: 'prueba' },
    { championsId: 'aurelionsol', history: 'prueba' },
    { championsId: 'azir', history: 'prueba' },
    { championsId: 'brand', history: 'prueba' },
    { championsId: 'braum', history: 'prueba' },
    { championsId: 'caitlyn', history: 'prueba' },
    { championsId: 'camile', history: 'prueba' },
    { championsId: 'cassiopeia', history: 'prueba' },
    { championsId: 'chogath', history: 'prueba' },
    { championsId: 'corki', history: 'prueba' },
    { championsId: 'darius', history: 'prueba' },
    { championsId: 'diana', history: 'prueba' },
    { championsId: 'drmundo', history: 'prueba' },
    { championsId: 'draven', history: 'prueba' },
    { championsId: 'ekko', history: 'prueba' },
    { championsId: 'elise', history: 'prueba' },
    { championsId: 'evelynn', history: 'prueba' },
    { championsId: 'ezreal', history: 'prueba' },
    { championsId: 'fiddlesticks', history: 'prueba' },
    { championsId: 'fiora', history: 'prueba' },
    { championsId: 'fizz', history: 'prueba' },
    { championsId: 'galio', history: 'prueba' },
    { championsId: 'gangplank', history: 'prueba' },
    { championsId: 'garen', history: 'prueba' },
    { championsId: 'gnar', history: 'prueba' },
    { championsId: 'gragas', history: 'prueba' },
    { championsId: 'graves', history: 'prueba' },
    { championsId: 'hecarim', history: 'prueba' },
    { championsId: 'heimerdinger', history: 'prueba' },
    { championsId: 'illaoi', history: 'prueba' },
    { championsId: 'irelia', history: 'prueba' },
    { championsId: 'ivern', history: 'prueba' },
    { championsId: 'janna', history: 'prueba' },
    { championsId: 'jarvaniv', history: 'prueba' },
    { championsId: 'jax', history: 'prueba' },
    { championsId: 'jayce', history: 'prueba' },
    { championsId: 'jhin', history: 'prueba' },
    { championsId: 'jinx', history: 'prueba' },
    { championsId: 'kaisa', history: 'prueba' },
    { championsId: 'kalista', history: 'prueba' },
    { championsId: 'karma', history: 'prueba' },
    { championsId: 'karthus', history: 'prueba' },
    { championsId: 'kassadin', history: 'prueba' },
    { championsId: 'katarina', history: 'prueba' },
    { championsId: 'kayle', history: 'prueba' },
    { championsId: 'kayn', history: 'prueba' },
    { championsId: 'kennen', history: 'prueba' },
    { championsId: 'khazix', history: 'prueba' },
    { championsId: 'kindred', history: 'prueba' },
    { championsId: 'kled', history: 'prueba' },
    { championsId: 'kogmaw', history: 'prueba' },
    { championsId: 'leblanc', history: 'prueba' },
    { championsId: 'leesin', history: 'prueba' },
    { championsId: 'leona', history: 'prueba' },
    { championsId: 'lissandra', history: 'prueba' },
    { championsId: 'lucian', history: 'prueba' },
    { championsId: 'lulu', history: 'prueba' },
    { championsId: 'lux', history: 'prueba' },
    { championsId: 'malphite', history: 'prueba' },
    { championsId: 'malzahar', history: 'prueba' },
    { championsId: 'maokai', history: 'prueba' },
    { championsId: 'masteryi', history: 'prueba' },
    { championsId: 'missfortune', history: 'prueba' },
    { championsId: 'mordekaiser', history: 'prueba' },
    { championsId: 'morgana', history: 'prueba' },
    { championsId: 'nami', history: 'prueba' },
    { championsId: 'nasus', history: 'prueba' },
    { championsId: 'nautilus', history: 'prueba' },
    { championsId: 'nidalee', history: 'prueba' },
    { championsId: 'nocturne', history: 'prueba' },
    { championsId: 'nunu', history: 'prueba' },
    { championsId: 'olaf', history: 'prueba' },
    { championsId: 'oriana', history: 'prueba' },
    { championsId: 'ornn', history: 'prueba' },
    { championsId: 'pantheon', history: 'prueba' },
    { championsId: 'poppy', history: 'prueba' },
    { championsId: 'pyke', history: 'prueba' },
    { championsId: 'quinn', history: 'prueba' },
    { championsId: 'rakan', history: 'prueba' },
    { championsId: 'rammus', history: 'prueba' },
    { championsId: 'reksay', history: 'prueba' },
    { championsId: 'renekton', history: 'prueba' },
    { championsId: 'rengar', history: 'prueba' },
    { championsId: 'riven', history: 'prueba' },
    { championsId: 'rumble', history: 'prueba' },
    { championsId: 'ryze', history: 'prueba' },
    { championsId: 'sejuani', history: 'prueba' },
    { championsId: 'shaco', history: 'prueba' },
    { championsId: 'shen', history: 'prueba' },
    { championsId: 'shyvana', history: 'prueba' },
    { championsId: 'singed', history: 'prueba' },
    { championsId: 'sion', history: 'prueba' },
    { championsId: 'sivir', history: 'prueba' },
    { championsId: 'skarner', history: 'prueba' },
    { championsId: 'sona', history: 'prueba' },
    { championsId: 'soraka', history: 'prueba' },
    { championsId: 'swain', history: 'prueba' },
    { championsId: 'syndra', history: 'prueba' },
    { championsId: 'tahmkench', history: 'prueba' },
    { championsId: 'taliyah', history: 'prueba' },
    { championsId: 'talon', history: 'prueba' },
    { championsId: 'taric', history: 'prueba' },
    { championsId: 'teemo', history: 'prueba' },
    { championsId: 'thresh', history: 'prueba' },
    { championsId: 'tristana', history: 'prueba' },
    { championsId: 'trundle', history: 'prueba' },
    { championsId: 'tryndamere', history: 'prueba' },
    { championsId: 'twistedfate', history: 'prueba' },
    { championsId: 'twitch', history: 'prueba' },
    { championsId: 'udyr', history: 'prueba' },
    { championsId: 'urgot', history: 'prueba' },
    { championsId: 'varus', history: 'prueba' },
    { championsId: 'vayne', history: 'prueba' },
    { championsId: 'veigar', history: 'prueba' },
    { championsId: 'velkoz', history: 'prueba' },
    { championsId: 'vi', history: 'prueba' },
    { championsId: 'viktor', history: 'prueba' },
    { championsId: 'vladimir', history: 'prueba' },
    { championsId: 'volibear', history: 'prueba' },
    { championsId: 'warwick', history: 'prueba' },
    { championsId: 'wukong', history: 'prueba' },
    { championsId: 'xayah', history: 'prueba' },
    { championsId: 'xerath', history: 'prueba' },
    { championsId: 'xinzhao', history: 'prueba' },
    { championsId: 'yasuo', history: 'prueba' },
    { championsId: 'yoric', history: 'prueba' },
    { championsId: 'zac', history: 'prueba' },
    { championsId: 'zed', history: 'prueba' },
    { championsId: 'ziggs', history: 'prueba' },
    { championsId: 'zilean', history: 'prueba' },
    { championsId: 'zoe', history: 'prueba' },
    { championsId: 'zyra', history: 'prueba' },
    { championsId: 'neeko', history: 'prueba' },
  ]
  testName = [

  ];

  constructor() { }

  ngOnInit() {
    for (let i = 0; i < this.champions.length; i++) {
      const element = this.champions[i].championsId;
      this.testName.push("{ nameChampion: " + element.toUpperCase() + " }");
    }
  console.log(this.testName);
  }

}
